name: bloc_weather_api
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  http: ^0.13.5
  #flutter_svg: ^1.1.5
  cloud_firestore: ^3.4.8
  firebase_auth: ^3.3.0
  firebase_storage: ^10.3.8
  firebase_core: ^1.22.0
  google_sign_in: ^5.4.1
  font_awesome_flutter: ^10.2.1
  provider: ^6.0.3
  #flutter_svg: ^0.19.3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    #default
    - assets/images/icons/default.png
    #nday
    - assets/images/icons/day/113.png
    - assets/images/icons/day/116.png
    - assets/images/icons/day/119.png
    - assets/images/icons/day/122.png
    - assets/images/icons/day/143.png
    - assets/images/icons/day/176.png
    - assets/images/icons/day/179.png
    - assets/images/icons/day/182.png
    - assets/images/icons/day/185.png
    - assets/images/icons/day/200.png
    - assets/images/icons/day/227.png
    - assets/images/icons/day/230.png
    - assets/images/icons/day/248.png
    - assets/images/icons/day/260.png
    - assets/images/icons/day/263.png
    - assets/images/icons/day/266.png
    - assets/images/icons/day/281.png
    - assets/images/icons/day/284.png
    - assets/images/icons/day/293.png
    - assets/images/icons/day/296.png
    - assets/images/icons/day/299.png
    - assets/images/icons/day/302.png
    - assets/images/icons/day/305.png
    - assets/images/icons/day/308.png
    - assets/images/icons/day/311.png
    - assets/images/icons/day/314.png
    - assets/images/icons/day/317.png
    - assets/images/icons/day/320.png
    - assets/images/icons/day/323.png
    - assets/images/icons/day/326.png
    - assets/images/icons/day/329.png
    - assets/images/icons/day/332.png
    - assets/images/icons/day/335.png
    - assets/images/icons/day/338.png
    - assets/images/icons/day/350.png
    - assets/images/icons/day/353.png
    - assets/images/icons/day/356.png
    - assets/images/icons/day/359.png
    - assets/images/icons/day/362.png
    - assets/images/icons/day/365.png
    - assets/images/icons/day/368.png
    - assets/images/icons/day/371.png
    - assets/images/icons/day/374.png
    - assets/images/icons/day/377.png
    - assets/images/icons/day/386.png
    - assets/images/icons/day/389.png
    - assets/images/icons/day/392.png
    - assets/images/icons/day/395.png
    #dem
    - assets/images/icons/night/113.png
    - assets/images/icons/night/116.png
    - assets/images/icons/night/119.png
    - assets/images/icons/night/122.png
    - assets/images/icons/night/143.png
    - assets/images/icons/night/176.png
    - assets/images/icons/night/179.png
    - assets/images/icons/night/182.png
    - assets/images/icons/night/185.png
    - assets/images/icons/night/200.png
    - assets/images/icons/night/227.png
    - assets/images/icons/night/230.png
    - assets/images/icons/night/248.png
    - assets/images/icons/night/260.png
    - assets/images/icons/night/263.png
    - assets/images/icons/night/266.png
    - assets/images/icons/night/281.png
    - assets/images/icons/night/284.png
    - assets/images/icons/night/293.png
    - assets/images/icons/night/296.png
    - assets/images/icons/night/299.png
    - assets/images/icons/night/302.png
    - assets/images/icons/night/305.png
    - assets/images/icons/night/308.png
    - assets/images/icons/night/311.png
    - assets/images/icons/night/314.png
    - assets/images/icons/night/317.png
    - assets/images/icons/night/320.png
    - assets/images/icons/night/323.png
    - assets/images/icons/night/326.png
    - assets/images/icons/night/329.png
    - assets/images/icons/day/332.png
    - assets/images/icons/night/335.png
    - assets/images/icons/night/338.png
    - assets/images/icons/night/350.png
    - assets/images/icons/night/353.png
    - assets/images/icons/night/356.png
    - assets/images/icons/night/359.png
    - assets/images/icons/night/362.png
    - assets/images/icons/night/365.png
    - assets/images/icons/night/368.png
    - assets/images/icons/night/371.png
    - assets/images/icons/night/374.png
    - assets/images/icons/night/377.png
    - assets/images/icons/night/386.png
    - assets/images/icons/night/389.png
    - assets/images/icons/night/392.png
    - assets/images/icons/night/395.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
